agent:
  id: "05-MS-core-CONTEXT_AGGREGATOR"
  name: "CONTEXT_AGGREGATOR"
  version: "0.1.0"
  description: "Curates/serves project memory and summaries."
  autodaemon: true
  roles: ["S"]

plugins:
  enabled: [core, http]  # add ai later if needed

network:
  host: "0.0.0.0"
  port: 3517

wiring:
  configuration_url: "http://configuration:3511"
  auth_jwks_url:     "http://auth_service:3512/.well-known/jwks.json"
  db_agg_ingest_url: "http://db_aggregator:3516/rpc/ingest"

logging:
  level: INFO
  oftx:
    local_state: "/app/data/state.db"
    purge_after_sync: true

heartbeat:
  interval_ms: 5000
