# Claude Neural Framework Enterprise Configuration
# -----------------------------------------
version: 2.0.0-beta.1
build: 2025.05.11.01

# Enterprise Licensing
license:
  check_interval: 86400  # License validation interval in seconds
  grace_period: 14       # Days to continue after license expiration
  features:              # Licensed enterprise features
    - multi_user
    - sso_integration
    - audit_logging
    - advanced_memory
    - data_sovereignty
    - premium_support

# Security Configuration
security:
  authentication:
    session_timeout: 3600      # Session timeout in seconds
    max_failed_attempts: 5     # Max failed login attempts before lockout
    lockout_duration: 1800     # Account lockout duration in seconds
    password_policy:
      min_length: 12
      require_mixed_case: true
      require_numbers: true
      require_symbols: true
      max_age_days: 90
      prevent_reuse: 10
  
  # Single Sign-On Configuration
  sso:
    enabled: false
    providers:
      - name: okta
        enabled: false
        client_id: ${CLAUDE_SSO_OKTA_CLIENT_ID}
        client_secret: ${CLAUDE_SSO_OKTA_CLIENT_SECRET}
        auth_url: https://your-domain.okta.com/oauth2/v1/authorize
        token_url: https://your-domain.okta.com/oauth2/v1/token
        jwks_url: https://your-domain.okta.com/oauth2/v1/keys
        user_info_url: https://your-domain.okta.com/oauth2/v1/userinfo
        scope: openid profile email
        
      - name: azure_ad
        enabled: false
        tenant_id: ${CLAUDE_SSO_AZURE_TENANT_ID}
        client_id: ${CLAUDE_SSO_AZURE_CLIENT_ID}
        client_secret: ${CLAUDE_SSO_AZURE_CLIENT_SECRET}
  
  # Transport Layer Security
  tls:
    min_version: TLSv1.2
    preferred_ciphers:
      - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
      - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
    certificate_path: /etc/claude/certs/server.crt
    key_path: /etc/claude/certs/server.key
  
  # Encryption Settings
  encryption:
    algorithm: AES-256-GCM
    key_rotation_days: 180
    data_at_rest: true
    key_management: local  # Options: local, aws_kms, azure_key_vault, hashicorp_vault
  
  # Audit Logging
  audit:
    enabled: true
    events:
      - user.login
      - user.logout
      - user.password_change
      - admin.user_create
      - admin.user_modify
      - admin.user_delete
      - system.config_change
      - system.backup
      - system.restore
      - memory.clear
      - memory.access
      - api.access
    retention_days: 365
    forward_to_siem: false
    siem_config:
      type: splunk  # Options: splunk, elastic, sumo
      endpoint: ${CLAUDE_SIEM_ENDPOINT}
      token: ${CLAUDE_SIEM_TOKEN}

# Storage and Memory Configuration
storage:
  memory_backend: postgres  # Options: postgres, redis, mongodb, file
  memory_compression: true
  memory_encryption: true
  
  # Database Configuration for Persistent Memory
  database:
    host: ${CLAUDE_DB_HOST:-localhost}
    port: ${CLAUDE_DB_PORT:-5432}
    name: ${CLAUDE_DB_NAME:-claude_enterprise}
    user: ${CLAUDE_DB_USER:-claude}
    password: ${CLAUDE_DB_PASSWORD}
    ssl_mode: verify-full
    connection_pool: 10
    timeout_seconds: 5
  
  # Backup Configuration
  backup:
    auto_backup: true
    interval_hours: 24
    retention_count: 30
    storage_path: /var/lib/claude/backups
    encryption: true
    compression: true
    include_user_data: true
    include_system_config: true

# Enterprise Compliance Configuration
compliance:
  data_residency:
    region: us  # Options: us, eu, ap
    enforce: true
  
  data_retention:
    user_profiles: 365  # Days to retain user profiles
    interaction_history: 180  # Days to retain interaction history
    agent_data: 90  # Days to retain agent data
    log_data: 365  # Days to retain logs
  
  privacy:
    data_minimization: true
    auto_anonymization: true
    pii_detection: true
    export_allowed: true
    delete_on_request: true

# Performance and Scaling
performance:
  max_concurrent_users: 100
  max_memory_per_user_mb: 512
  cpu_allocation_strategy: adaptive  # Options: fixed, adaptive
  auto_scaling: true
  load_balancing: true
  rate_limiting:
    enabled: true
    requests_per_minute: 60
    burst: 100

# Monitoring and Alerting
monitoring:
  health_check_interval: 60  # Seconds
  metrics:
    enabled: true
    prometheus_endpoint: /metrics
    collection_interval: 15  # Seconds
  
  alerting:
    channels:
      email:
        enabled: true
        recipients: ${CLAUDE_ALERT_EMAIL_RECIPIENTS}
      slack:
        enabled: false
        webhook: ${CLAUDE_ALERT_SLACK_WEBHOOK}
      pagerduty:
        enabled: false
        service_key: ${CLAUDE_ALERT_PAGERDUTY_KEY}
    
    alerts:
      - name: high_memory_usage
        description: Memory usage exceeds threshold
        threshold: 85  # Percentage
        duration: 300  # Seconds
        severity: warning
      
      - name: license_expiring
        description: Enterprise license approaching expiration
        threshold: 15  # Days
        severity: critical
      
      - name: failed_login_attempts
        description: Multiple failed login attempts detected
        threshold: 10  # Count in 5 minutes
        severity: warning

# Support Configuration
support:
  enabled: true
  portal_url: https://support.claudeframework.com
  contact_email: enterprise-support@claudeframework.com
  priority_access: true
  response_times:
    critical: 1  # Hours
    high: 4      # Hours
    medium: 8    # Hours
    low: 24      # Hours