agent:
  id: "06-MS-service-DB_AGGREGATOR"
  name: "DB_AGGREGATOR"
  version: "0.1.0"
  description: "Durable central store for deltas, events, and context."
  autodaemon: true
  roles: ["S"]

plugins:
  enabled: [core, http]

network:
  host: "0.0.0.0"
  port: 3516

wiring:
  configuration_url: "http://configuration:3511"
  auth_jwks_url:     "http://auth_service:3512/.well-known/jwks.json"
  db_agg_ingest_url: "http://db_aggregator:3516/rpc/ingest"

logging:
  level: INFO
  oftx:
    local_state: "/app/data/state.db"
    purge_after_sync: false  # the central DB retains history

heartbeat:
  interval_ms: 5000
